### ISSUE TITLE
Azure CDN automatically caches file without easy option to disable

### ISSUE THREAD

**Issue by sarahxxu** [adobe/aio-lib-files#57]
### Expected Behaviour

User should be able to select whether they'd like the file to be cached. 

### Actual Behaviour

Currently, it seems that Azure CDN caches the files by default.

**Comment by sarahxxu** [comment]
We are investigating with the Azure support about the best way to disable it or to automate a regular purge (ongoing with our DevOps team)

**Comment by meryllblanchet** [comment]
Done. @sarahxxu: proposal for a future enhancement (to address in a different issue): enhance the SDK API to let developers programmatically manage caching rules for their own  container.
However, it will need a feasibility study upfront.
