### ISSUE TITLE
aio library files preview instead of continuous download of library cloud items

### ISSUE THREAD

**Issue by mdresch** [adobe/aio-lib-files#63]
The current cloud library is downloaded to the file menu when going through a directory instead of just downloading a preview of the file it will download its entire content to its file directory.

The conflicts this causes when clients settings have been adjusted in the operating system to only download files when they are used is the reason why a client would not be able to continue using the application. A large library which is downloaded to a clients machine could run out of disc space in no time if some of the library content is instantly downloaded. 

Either advise clients the content will always be downloaded to a set directory and explain the settings in the operating system will have no effect when using the lib-files or update the application library files so it behaves in accordance to the operating system settings.

**Comment by sarahxxu** [comment]
Hi @mdresch I'm not sure that I understand fully. Could you share some more code examples or details? What function did you use and what's the error?

**Comment by mdresch** [comment]
Hi @sarahxxu I will follow up on your request as the code and the examples I will be able to provide will not be a error message in current files and menu file handling A good example was made available in a word document. Which I would be glad to share but for now there is no error message that will explain the details which are required to change. The errors and slow system responses I had to experience and a list of support tickets in the community pages is all that is available.

**Comment by meryllblanchet** [comment]
Hi @mdresch , I am a bit confused too. Could you describe what use-case you are trying to solve with this library?

**Comment by mdresch** [comment]
Hi @meryllblanchet, thank you for you response. I have to say its more details then I seem to be able to explain briefly. Sorry about that I will get back as soon as possible to provide a few examples to the differences amount of disk size and downloads to a client machine / user machine. I have a few from sync methodologies and seems to all conflict with each one of the systematics seems more beneficial then the other.

**Comment by meryllblanchet** [comment]
Closing the issue due to lack of clarity. Please make sure that you provide the required information when opening an issue against our repositories.
