### ISSUE TITLE
New R/W pre-signed URL support requires the `x-ms-blob-type` header with PUT

### ISSUE THREAD

**Issue by bobvanmanen** [adobe/aio-lib-files#67]
### Expected Behaviour

This should work:

```
const url = await files.generatePresignURL('test.png', {
     expiryInSeconds: 60,
     permissions: 'rwd'
});
await axios.put(url, { hello: 'world' });
```

### Actual Behaviour

It fails because `x-ms-blob-type: BlockBlob` is a required header. See: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

#### Platform and Version

This is an Azure API requirement.

**Comment by alexkli** [comment]
Note that you can add the header in to the presigned url. The azure implementation i side aio-lib-files can do this when it presigns a PUT, as it inly deals with blobs here. This makes it transparent and backwards compatible.

**Comment by sandeep-paliwal** [comment]
@alexkli The Azure SAS only allows to specify few response headers, in this case we will need to support request headers, so it won't be possible to fix this in sdk. ref [sas doc](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specifying-query-parameters-to-override-response-headers-blob-and-file-services-only)

Let me know if I am wrong here.

**Comment by meryllblanchet** [comment]
Meanwhile, we will release a config change at CDN level as discussed above in the ticket.
If we confirm there's a way to make it at SDK library level, we'll implement it as a second step to automatically provide a similar support in both OOTB and Bring Your Own storages.

**Comment by meryllblanchet** [comment]
@bobvanmanen the fix is in place at CDN level, could you please give it a new try and confirm that your requests are executed as expected?

**Comment by alexkli** [comment]
@meryllblanchet are these presigned URLs always going through a CDN? For clients inside data centers (which is the case for Nui) this will be slower than direct Azure BS or AWS S3 URLs.

**Comment by meryllblanchet** [comment]
@alexkli for now yes. We're waiting on first concrete performance feedback (e.g. Nui workers) to work on and provide optimization features.

FYI, we have https://github.com/adobe/aio-lib-files/pull/65 in case this will be effectively needed, but we are also considering a tighter integration between the SDK and Runtime capabilities to serve the files (wether with or without CDN) in a more seamless manner to the end-users/systems.
