### ISSUE TITLE
files.copy returns 414 for own storage

### ISSUE THREAD

**Issue by UrsBoller** [adobe/aio-lib-files#72]
### Expected Behaviour
I want to copy a file from one folder to another using files.copy and my own storage account (azure)

### Actual Behaviour
files works as expected with own credentials. but when I try to copy a file from `folderA` to `folderB` I just get an error as follow
`[FilesLib:ERROR_INTERNAL] unknown error response from provider with status: 414`

### Reproduce Scenario (including but not limited to)
here is the sample code I try to run (the source file exists)
`await files.copy('folderA/myFile.json','folderB/')`

#### Steps to Reproduce
1) init files using own azure storage account
2) try to copy a file

#### Platform and Version
using `"@adobe/aio-lib-files": "^1.2.3"`
more info from "aio info":
` System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 8.14 GB / 15.84 GB
  Binaries:
    Node: 12.16.2
    Yarn: 1.22.0
    npm: 6.14.4
  Virtualization:
    Docker: 19.03.13
  npmGlobalPackages:
    @adobe/aio-cli: Not Found
  CLI plugins:
    @adobe/aio-cli 5.0.1 (core)
    @adobe/aio-cli-plugin-app 4.0.0 (user)
    @adobe/aio-cli-plugin-auth 2.4.0 (core)
    @adobe/aio-cli-plugin-certificate 0.2.0 (core)
    @adobe/aio-cli-plugin-config 2.3.0 (core)
    @adobe/aio-cli-plugin-console 3.2.0 (core)
    @adobe/aio-cli-plugin-events 1.1.0 (core)
    @adobe/aio-cli-plugin-info 1.1.1 (core)
    @adobe/aio-cli-plugin-runtime 3.0.0 (core)`

#### Sample Code that illustrates the problem
`await files.copy('folderA/myFile.json','folderB/')`

#### Logs taken while reproducing problem
`error: [FilesLib:ERROR_INTERNAL] unknown error response from provider with status: 414`

**Comment by UrsBoller** [comment]
issue solved, the error was sitting in front of the computer ...

**Comment by meryllblanchet** [comment]
@UrsBoller , you're getting faster than us to solve issues! ;-)
