### ISSUE TITLE
presignedUrl file path must already exist

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-lib-files#88]
### Expected Behaviour
it should be possible to get a presignedUrl with write permission for a file that has not yet been created.

### Actual Behaviour
an error is thrown

### Reproduce Scenario (including but not limited to)
```
const rwdPresignUrl = await files.generatePresignURL('dir_could_not_exist/file_does_not_exist_yet.txt', {
  expiryInSeconds: 3600, 
  permissions: 'rwd'
})
```

### Workaround
write to the file before getting the url
```
await files.write('dir_could_not_exist/file_does_not_exist_yet.txt', '')
const rwdPresignUrl = await files.generatePresignURL('dir_could_not_exist/file_does_not_exist_yet.txt', {
  expiryInSeconds: 3600, 
  permissions: 'rwd' 
})
```

**Comment by meryllblanchet** [comment]
Feedback from @sandeep-paliwal :

You should be able to generate presign URLs for non existent files with 'rwd' permission. To write you can just make a PUT call to the generated URL with required file data. I gave it a try and it works fine. Here is  sample code:

```
const presignUrl = await files.generatePresignURL('non-existent-folder/non-existent-file1.txt', { expiryInSeconds: 3600,
    permissions: 'rwd'}) 
```

Now use this URL to write to the file, here is sample CURL for writing plain text data:

```
curl --location --request PUT '<presign URL>' \
--header 'Content-Type: text/plain' \
--data-raw 'Test file write for non existent file and folder'
```

Does that solve the issue?
